### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by Ezioer** [hlc0000/SwiftlyCache#1]
很好用，支持一下

**Comment by hlc0000** [comment]
谢谢支持,如果可以,帮忙推荐给身边的iOS的朋友呗

**Comment by hlc0000** [comment]
> 很好用，支持一下
谢谢支持，如果身边有iOS朋友需要用到的可以帮忙推荐一下

**Comment by CirclesInTheSand** [comment]
I thought we should post issues here?

**Comment by hlc0000** [comment]
If you have any questions, you can directly raise them here





> I thought we should post issues here?

If you have any questions, you can directly raise them here

**Comment by hlc0000** [comment]
If you have any questions, you can directly raise them here
