### ISSUE TITLE
正在抽空学习老哥的swift代码

### ISSUE THREAD

**Issue by b593771943** [hlc0000/SwiftlyCache#3]
有木有什么建议

**Comment by hlc0000** [comment]
其实SwiftlyCache的代码不是很复杂的

**Comment by hlc0000** [comment]
> 有木有什么建议

SwiftlyCache中的逻辑其实还是比较简单的,如果你有什么问题可以在这里提问也可以直接加我微信问我,下面是我微信号:
h825307326

**Comment by b593771943** [comment]
好的。一开始大致看了下，觉得里面有一些算法思想以及swift语法及代码书写规范很适合模仿学习
