### ISSUE TITLE
swift package方式导入会报错

### ISSUE THREAD

**Issue by sunjianan9900** [hlc0000/SwiftlyCache#4]
错误：
Showing All Messages
https://github.com/hlc0000/SwiftlyCache.git has no Package.swift manifest for version 1.1.8

**Comment by hlc0000** [comment]
> 错误：
> 显示所有消息
> https://github.com/hlc0000/SwiftlyCache.git没有版本1.1.8的Package.swift清单

是的，现在该项目还没有使用Package的方式引入，目前比较忙，所以使用Package引入的功能应该会再过一段时间才会实现。

**Comment by hlc0000** [comment]
是的，现在该项目还没有使用Package的方式约会，目前比较忙，所以使用Package的功能应该会再过一段时间才会加入

**Comment by sunjianan9900** [comment]
> 是的，现在该项目还没有使用Package的方式约会，目前比较忙，所以使用Package的功能应该会再过一段时间才会加入

好的～ 通过拖拽方式导入了，我先用用看
