### ISSUE TITLE
根据key查找value不正确：

### ISSUE THREAD

**Issue by welljobs** [hlc0000/SwiftlyCache#7]
根据当天日期（年月日）+  ID 作为key来存录像，有点日期查询不对，比如我查22号，读出来的数据是21号的，我看了一下这个走的是内存缓存，链表的，可是我没找到问题，麻烦作者帮忙看看
![image](https://user-images.githubusercontent.com/19242491/221134003-14ab476a-339d-4dea-82a2-ab15aa7f92fc.png)
![image](https://user-images.githubusercontent.com/19242491/221135042-c9bb725b-dce2-4671-b186-7e94d0d04f91.png)

**Comment by hlc0000** [comment]
你好，我刚刚测了一下，结果是没有问题的呀

**Comment by hlc0000** [comment]
![image](https://user-images.githubusercontent.com/50684887/221340329-dc5b8581-f5b7-42b6-8776-1c9fc7e438d3.jpeg)

**Comment by hlc0000** [comment]
我下午测一测

**Comment by hlc0000** [comment]
你好，我刚刚简单测了一下，数据存取是正常的!![image](https://user-images.githubusercontent.com/50684887/221342803-087338ab-d0de-4cc3-9393-d2b865e64f09.jpeg)

**Comment by hlc0000** [comment]
![image](https://user-images.githubusercontent.com/50684887/221342869-09d2cf8a-048a-43d3-817f-a4fc6a87ff95.jpeg)

**Comment by welljobs** [comment]
那我再家查一下，辛苦了

**Comment by welljobs** [comment]
那我再家查一下，辛苦了

**Comment by hlc0000** [comment]
如果没有什么问题我就把这个提问给关了

**Comment by welljobs** [comment]
ok
